---
apiVersion: v1
kind: Namespace
metadata:
  name: app-llm
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-llm
  namespace: app-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-llm
  template:
    metadata:
      labels:
        app: app-llm
    spec:
      containers:
        - name: ollama
          image: davidaavilar/app-llm
          ports:
            - containerPort: 11434
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: app-llm
  namespace: app-llm
spec:
  type: ClusterIP
  selector:
    app: app-llm
  ports:
    - port: 11434
      targetPort: 11434