# FROM davidaavilar/gim-openjdk25-multibase-hardened:candidate-2026w23-abf1c55f

# WORKDIR /opt/app

# CMD ["java", "-version"]

FROM debian:trixie

WORKDIR /app

CMD ["sh", "-c", "echo 'Debian Trixie funcionando'; cat /etc/os-release; whoami; id"]