name: Prisma Cloud IaC Scan

on:
  push:
    branches: [ "github" ]
  # pull_request:
  #   branches: [ "github" ]

permissions:
  contents: read

jobs:
  prisma_cloud_iac_scan:
    permissions:
      contents: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    name: Run Prisma Cloud Code Scan to check
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Prisma Cloud 
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api4.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          use_enforcement_rules: true
          compact: true
          quiet: true
